# Generated by Django 5.1.2 on 2024-10-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do artigo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='artigos_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da pessoa')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('registro_profissional', models.CharField(blank=True, max_length=20, verbose_name='Registro Profissional')),
                ('imagem', models.ImageField(upload_to='equipe_fotos/', verbose_name='Foto da pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='LegendaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da legenda do banner')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaisApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='artigos/')),
            ],
        ),
        migrations.CreateModel(
            name='NossasFerramentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.CharField(default='', max_length=50, verbose_name='Texto ferramenta normal')),
                ('destaque', models.CharField(default='', max_length=50, verbose_name='Texto ferramenta destaque')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='PlataformaJogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Subtítulo')),
            ],
        ),
        migrations.CreateModel(
            name='PlataformaVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Subtítulo')),
            ],
        ),
    ]
