# Generated by Django 5.1.2 on 2024-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do produto')),
                ('descricao', models.TextField()),
                ('preco', models.IntegerField()),
                ('data_produto', models.DateTimeField()),
            ],
        ),
    ]
