# Generated by Django 5.1.2 on 2024-10-09 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_produto',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 10, 9, 19, 35, 22, 31389)),
        ),
    ]
