# Generated by Django 5.1.2 on 2024-10-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_data_produto_remove_produto_preco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da pessoa')),
                ('descricao', models.TextField()),
                ('crp', models.CharField(default='', max_length=11, verbose_name='CRP da pessoa')),
                ('foto', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
