# Generated by Django 5.1.2 on 2024-10-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_pessoas_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da pessoa')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('registro_profissional', models.CharField(blank=True, max_length=20, verbose_name='Registro Profissional')),
                ('foto', models.ImageField(upload_to='equipe_fotos/', verbose_name='Foto da pessoa')),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoas',
        ),
    ]
