# Generated by Django 5.1.2 on 2024-10-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_remove_nossasferramentas_ferramenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigos',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='nossasferramentas',
            name='destaque',
            field=models.CharField(default='', max_length=50, verbose_name='Texto ferramenta destaque'),
        ),
        migrations.AlterField(
            model_name='nossasferramentas',
            name='normal',
            field=models.CharField(default='', max_length=50, verbose_name='Texto ferramenta normal'),
        ),
    ]
