# Generated by Django 5.1.2 on 2024-10-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_artigos_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='artigos_fotos/'),
        ),
    ]
