# Generated by Django 5.1.2 on 2024-10-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_artigos_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='foto',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='plataformajogos',
            old_name='subtitulo',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='plataformavideos',
            old_name='subtitulo',
            new_name='descricao',
        ),
    ]
