# Generated by Django 5.1.2 on 2024-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_foto_alter_produto_data_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='crp',
            field=models.CharField(default='', max_length=11, verbose_name='CRP da pessoa'),
        ),
    ]
